name: Publish OCI Image

on:
  push:
    branches:
      - "master"

jobs:
  build_and_publish:
    name: Build and Publish OCI Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.YOUR_TOKEN }}
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: Install Dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -q -y && sudo apt-get install -q -y \
            qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/midou36o/drasl:latest -f Dockerfile .
          docker images  # List images to verify

      - name: Log in to GitHub Container Registry
        env:
          GHCR_TOKEN: ${{ secrets.YOUR_TOKEN }}
        run: echo "$GHCR_TOKEN" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/midou36o/drasl:latest
          docker images
