name: Publish Docker Image

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.YOUR_TOKEN }}

      - name: Build Docker image with Nix
        run: |
          # Build the OCI image
          nix build .#oci

          # Get the output path of the OCI image
          oci_image=$(nix build --no-link --print-out-paths .#oci)
          echo "OCI Image Path: $oci_image"

          # Push the OCI image to GHCR
          buildah push "$oci_image" "ghcr.io/midou36o/drasl:latest"

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.YOUR_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/midou36o/drasl:latest
