name: Publish OCI image

on:
  push:
    branches:
      - "master"

jobs:
  push_to_registry:
    name: Push OCI image to GHCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/midou36o/drasl
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Debug Tags
        run: |
          echo "Generated Tags: ${{ steps.meta.outputs.tags }}"

      - name: Build and Push OCI Image with Verbose Logging
        env: 
          REFERENCES: ${{ steps.meta.outputs.tags }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          buildah --log-level debug login -u "${{ github.actor }}" --password "$GITHUB_TOKEN" ghcr.io
          buildah --log-level debug manifest create drasl
          for system in 'x86_64-linux' 'aarch64-linux'; do 
            oci_archive="$(nix build --no-link --print-out-paths ".#oci-cross-$system")"
            buildah --log-level debug manifest add drasl "docker-archive:$oci_archive"
          done
          echo "done!"

          # Debugging: Print the REFERENCES variable
          echo "REFERENCES: $REFERENCES"
          
          # Push the multi-arch image to GHCR using the latest tag
          buildah --log-level debug manifest push --all -f v2s2 drasl "docker://ghcr.io/midou36o/drasl:latest"
          echo "Pushed as latest"
