name: Publish Docker Image

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.YOUR_TOKEN }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - name: Build OCI image with Nix
        run: |
          # Build the OCI image
          nix build .#oci

          # Find the output path of the OCI image
          oci_image_path=$(nix build --no-link --print-out-paths .#oci | grep -oP '(?<=/nix/store/)[^ ]+')
          echo "OCI Image Path: /nix/store/$oci_image_path"

          # Verify the image file exists
          if [ ! -f "/nix/store/$oci_image_path" ]; then
            echo "OCI image file does not exist."
            exit 1
          fi

          # Import the OCI image into Buildah
          buildah from scratch --name drasl-imported
          buildah add drasl-imported "/nix/store/$oci_image_path"
          buildah config --label "version=latest" drasl-imported
          buildah tag drasl-imported ghcr.io/midou36o/drasl:latest

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.YOUR_TOKEN }}

      - name: Push Docker Image
        run: |
          # Push the image to GHCR
          buildah push ghcr.io/midou36o/drasl:latest
